export default actionType = { 
    CREATE_NEW_ROOM: "CREATE_NEW_ROOM",
    CREATE_ROOM_SUCCESS: "CREATE_ROOM_SUCCESS",
    GET_ALL_ROOMS: "GET_ALL_ROOMS",
    GET_ALL_ROOMS_SUCCESS: "GET_ALL_ROOMS_SUCCESS",
    ENTER_ROOM: "ENTER_ROOM",

    CONNECT_TO_TCP_SOCKET: "CONNECT_TO_TCP_SOCKET",
    DISCONNECT_TO_TCP_SOCKET: "DISCONNECT_TO_TCP_SOCKET",
    CONNECT_TO_TCP_SOCKET_SUCCESS: "CONNECT_TO_TCP_SOCKET_SUCCESS",
    RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
    SOCKET_ERROR: "SOCKET_ERROR",
    SOCKET_CLOSED: "SOCKET_CLOSED",

    SAVE_MESSAGE: "SAVE_MESSAGE",
    GET_CHAT_HISTORY: "GET_CHAT_HISTORY",
    GET_CHAT_HISTORY_SUCCESS: "GET_CHAT_HISTORY_SUCCESS",  

    ACTION_SUCCESS: "ACTION_SUCCESS",
    ACTION_FAIL: "ACTION_FAIL"
}